export const symbols = {
  0: [
    true, true, true,
    true, false, true,
    true, false, true,
    true, false, true,
    true, true, true,
  ],
  1: [
    false, false, true,
    false, false, true,
    false, false, true,
    false, false, true,
    false, false, true,
  ],
  2: [
    true, true, true,
    false, false, true,
    true, true, true,
    true, false, false,
    true, true, true,
  ],
  3: [
    true, true, true,
    false, false, true,
    true, true, true,
    false, false, true,
    true, true, true,
  ],
  4: [
    true, false, true,
    true, false, true,
    true, true, true,
    false, false, true,
    false, false, true,
  ],
  5: [
    true, true, true,
    true, false, false,
    true, true, true,
    false, false, true,
    true, true, true,
  ],
  6: [
    true, false, false,
    true, false, false,
    true, true, true,
    true, false, true,
    true, true, true,
  ],
  7: [
    true, true, true,
    false, false, true,
    false, false, true,
    false, false, true,
    false, false, true,
  ],
  8: [
    true, true, true,
    true, false, true,
    true, true, true,
    true, false, true,
    true, true, true,
  ],
  9: [
    true, true, true,
    true, false, true,
    true, true, true,
    false, false, true,
    false, false, true,
  ],
  ':': [
    false, false, false,
    false, true, false,
    false, false, false,
    false, true, false,
    false, false, false,
  ],
  '*': [
    false, true, true,
    false, true, true,
    false, false, false,
    false, false, false,
    false, false, false,
  ],
  '-': [
    false, false, false,
    false, false, false,
    false, true, false,
    false, false, false,
    false, false, false,
  ],
  ' ': [
    false, false, false,
    false, false, false,
    false, false, false,
    false, false, false,
    false, false, false,
  ],
  a: [
    true, true, true,
    true, false, true,
    true, true, true,
    true, false, true,
    true, false, true,
  ],
  b: [
    true, true, false,
    true, false, true,
    true, true, false,
    true, false, true,
    true, true, false,
  ],
  c: [
    true, true, true,
    true, false, false,
    true, false, false,
    true, false, false,
    true, true, true,
  ],
  d: [
    true, true, false,
    true, false, true,
    true, false, true,
    true, false, true,
    true, true, false,
  ],
  e: [
    true, true, true,
    true, false, false,
    true, true, false,
    true, false, false,
    true, true, true,
  ],
  f: [
    true, true, true,
    true, false, false,
    true, true, false,
    true, false, false,
    true, false, false,
  ],
  g: [
    true, true, true,
    true, false, false,
    true, false, true,
    true, false, true,
    true, true, true,
  ],
  h: [
    true, false, true,
    true, false, true,
    true, true, true,
    true, false, true,
    true, false, true,
  ],
  i: [
    false, true, false,
    false, true, false,
    false, true, false,
    false, true, false,
    false, true, false,
  ],
  j: [
    true, true, true,
    false, false, true,
    false, false, true,
    true, false, true,
    true, true, true,
  ],
  k: [
    true, false, true,
    true, false, true,
    true, true, false,
    true, false, true,
    true, false, true,
  ],
  l: [
    true, false, false,
    true, false, false,
    true, false, false,
    true, false, false,
    true, true, true,
  ],
  m: [
    true, false, true,
    true, true, true,
    true, false, true,
    true, false, true,
    true, false, true,
  ],
  n: [
    true, false, true,
    true, false, true,
    true, true, true,
    true, true, true,
    true, false, true,
  ],
  o: [
    true, true, true,
    true, false, true,
    true, false, true,
    true, false, true,
    true, true, true,
  ],
  p: [
    true, true, true,
    true, false, true,
    true, true, true,
    true, false, false,
    true, false, false,
  ],
  q: [
    true, true, true,
    true, false, true,
    true, false, true,
    true, true, true,
    true, true, true,
  ],
  r: [
    true, true, true,
    true, false, true,
    true, true, true,
    true, true, false,
    true, false, true,
  ],
  s: [
    true, true, true,
    true, false, false,
    true, true, true,
    false, false, true,
    true, true, true,
  ],
  t: [
    true, true, true,
    false, true, false,
    false, true, false,
    false, true, false,
    false, true, false,
  ],
  u: [
    true, false, true,
    true, false, true,
    true, false, true,
    true, false, true,
    true, true, true,
  ],
  v: [
    true, false, true,
    true, false, true,
    true, false, true,
    true, false, true,
    false, true, false,
  ],
  w: [
    true, false, true,
    true, false, true,
    true, false, true,
    true, true, true,
    true, false, true,
  ],
  x: [
    true, false, true,
    true, false, true,
    false, true, false,
    true, false, true,
    true, false, true,
  ],
  y: [
    true, false, true,
    true, false, true,
    true, true, true,
    false, true, false,
    false, true, false,
  ],
  z: [
    true, true, true,
    false, false, true,
    false, true, false,
    true, false, false,
    true, true, true,
  ],
}
